# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - shell_scripts/*
    - config/*
    - sql/*
    - Postgresql_functions/*
    - python/*


pool:
  name: Optumera
  demands: Agent.Name -equals Optumera_Dev_Linux01
  
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      for f in $(git diff --name-only HEAD HEAD~15)
      #for f in $(git diff --stat HEAD~5 HEAD)
      do
        echo "$f"
        case "$_" in
                shell_scripts/*)
                echo "this is A"
                #cp -r $(Build.SourcesDirectory)/A $(Build.ArtifactStagingDirectory)
                ;;
                
                config/*)
                echo "this is B"
                #cp -r $(Build.SourcesDirectory)/B $(Build.ArtifactStagingDirectory)
                ;;
                sql/*)
                echo "this is C"
                #cp -r $(Build.SourcesDirectory)/C $(Build.ArtifactStagingDirectory)
                ;;
                Postgresql_functions/*)
                echo "this is D"
                #cp -r $(Build.SourcesDirectory)/D $(Build.ArtifactStagingDirectory)
                ;;
                python/*)
                echo "this is E"
                #cp -r $(Build.SourcesDirectory)/D $(Build.ArtifactStagingDirectory)
                ;;
        esac
      done