# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - OptumeraETL/shell_scripts/*
    - OptumeraETL/config/*
    - OptumeraETL/sql/*
    - OptumeraETL/Postgresql_functions/*


pool:
  name: Optumera
  demands: Agent.Name -equals Optumera_Dev_Linux01
  
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      for f in $(git diff HEAD HEAD~ --name-only)
      do
        echo $f
        case "$_" in
                OptumeraETL/shell_scripts/*)
                echo this is A
                cp -r $(Build.SourcesDirectory)/A $(Build.ArtifactStagingDirectory)
                ;;
                
                OptumeraETL/config/*)
                echo this is B
                cp -r $(Build.SourcesDirectory)/B $(Build.ArtifactStagingDirectory)
                ;;
                OptumeraETL/sql/*)
                echo this is C
                cp -r $(Build.SourcesDirectory)/C $(Build.ArtifactStagingDirectory)
                ;;
                OptumeraETL/Postgresql_functions/*)
                echo this is d
                cp -r $(Build.SourcesDirectory)/D $(Build.ArtifactStagingDirectory)
                ;;
        esac
      done
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      **
      !.git/**/*
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    OverWrite: true
    #CleanTargetFolder: true
    #preserveTimestamp: false
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: optumeraETL_artifact